---
title: "A Broad Introduction to Bayesian Statistics"
author: "Matthew Gonnerman"
date: "1/16/2022"
output:
  html_document: default
  pdf_document: default
  df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

_A Note to Readers: This module is a work in progress_

### Outline:
[Objectives]      
[Known and Unknown Information]  
[A Frequentist Approach]  
[A Bayesian Approach]  
[MCMC: Sampling from the Posterior]  
[Bayesian vs Frequentist]  
[Sources and Other Resources]  

### Objectives

This module is intended as a starting point for learning about Bayesian statistics, specifically aimed at graduate students studying ecology who are unfamiliar or uncomfortable with statistics in general. It should not be considered a comprehensive description but rather as a means of entry that hopefully will give you confidence to further explore these concepts. I have stripped away much of the details about methods and derivation of equations to make this more of a summary of how different statistical philosophies approach a problem. To that end, I wrote this module with the following objectives in mind...   
  
<div style="margin-left: 1em;"> 1) To provide a broad, introductory description of Bayesian philosophy.  
2) To breakdown the mechanisms by which Bayesian statistics functions as well as provide a brief summary of one of its most commonly used tools, Markov chain Monte Carlo simulations.  
3) To differentiate a Bayesian approach from the more commonly taught Frequentist approach.  
4) _To force myself to better understand these concepts and to learn RMarkdown in the process (This one is just for me, but at least now you know why someone would do this in the first place)._ </div>

### Known and Unknown Information

If you are reading this module, I assume you are either being forced to or you are a graduate student with a need or desire to better understand your options when conducting analyses. While we all are working with different study systems and animals, we have some things in common. First, we had to write a research proposal describing a statistical approach that we did not yet understand because our adviser suggested it to us. Second, we have a series of questions we hope to answer to aid in the management of our systems. And third, we possess (or will collect) data sets from our systems which we will use to answer our research questions. For example, I studied population and movement ecology of game birds and focused on questions relating to the composition and distribution of wild turkey populations, such as how they use different land cover types throughout the year. To that end, I collected data on turkey locations using GPS and VHF radio-telemetry which, in combination with remotely sensed data products such as the National Land Cover Database, represented the data I had available to describe my system.

Regardless of the system we wish to study, information can be broken down into two categories: what is known and what is unknown. In the case of our turkey example, the knowns are turkey locations, individual turkey characteristics, and associated land cover at each location. The unknowns are the underlying relationships that define how these two data sets relate to one another. Do turkeys select for a given land cover type consistently more than others? Is there some effect of weather on selection? Maybe a turkey's sex or age affects their decision-making process? What about time of day? While in practice these decisions can be described using increasingly complex modeling techniques, we can simplify a decision to a weighted coin flip describing whether a turkey would select one option over another. For the sake of being on the same page, lets use this system and data as an example throughout the module to describe these coin flips. Specifically, we wish to know how much the presence of snow impacts a turkey's use of forested over other land cover options. 

So now we have our data and the research question we wish to answer, but we still need to determine how we will approach our analysis (ideally this is done in the planning stage of your research). Within the field of ecology, we tend to choose an approaches that fall within one of two paradigms, bayesian or frequentist statistics. There are many similarities and distinctions  in the methods used between the two (which we will summarize at the end of this module), but the core difference lies in how each approaches known and unknown information. 

### A Frequentist Approach

A frequentist would look at our turkey resource selection question and say that there is some fixed parameter, $\theta$, that describes the effect size of snow depth on selection for forests. By fixed, we mean that there is some true value for $\theta$ that applies to our study system. We do not know it, but it exists (even if it is 0). We then treat our collected data, y, as random variables which are drawn from some larger pool of possible data. The data is random because if we were to go back out and collect new data, we would almost certainly get a different data set due to any number of factors such as measurement error, predator presence, or individual behavioral differences. We can describe the relationship between our known and unknown information using a probability statement, $Pr(y|\theta)$, which reads "the probability of collecting our observed data assuming some unknwon value for $\theta$."

This probability statement alone doesn't do much for us because we don't know what $\theta$ is. However, it can be rewritten as a **likelihood function**, $L(\theta|y)$, which now makes our parameter dependent on the data we collected. This reads as "the likelihood of a parameter value given the data" and is equivalent to our probability statement, $L(\theta|y) = Pr(y|\theta)$. By re-framing our known and unknown information in this way, we can ask what value of  $\theta$ is the most likely to be true given the data we collected. By reversing the dependencies, we can use our model to ask how likely our data set is for a given value of of $\theta$. In terms of our research question, what relationship between turkey habitat selection and snow best describes the location information that we collected. We can compare likelihoods across different values for $\theta$ to find which value maximizes the likelihood. The exact steps to this process are more involved and involve some math that I will not cover here, but for more information search for **Maximum Likelihood Estimators (MLE)**. 

Estimating the value for $\theta$ that maximizes the likelihood is only half of what we need to answer our research question. The other half is defining our uncertainty in that estimate, which can be described using **confidence intervals**. A confidence interval is just the range of values defining $\theta$ that fall within some arbitrary level of certainty we wish to apply to the model. Again, the exact methods for determining confidence intervals are not relevant. What is important to understand is that any measure of uncertainty we provide is evaluated and described in terms of the frequency of hypothetical replicates of our data (hence the term frequentist). If we were to go out and re-sample turkey locations, what values of $\theta$ would result in producing the same or similar data. It is important to note here, we are still considering $\theta$ a fixed value, we are just hedging our bets as to what that value actually is.

### A Bayesian Approach

A Bayesian approach is going to start in a very similar place as a frequentist one. We have known data (y), a parameter we wish to describe ($\theta$), and a model defining our hypothesized relationship between the two. Where we will deviate from frequentist is in how we treat $\theta$. Instead of seeking to define a fixed value around which there is some uncertainty (i.e. Frequentist), we instead are looking to define some probability distribution that describes our parameter. This distinction may not be immediately obvious, but it affects how we describe our results. Whereas frequentists make statements about the probability of observing certain data given values of $\theta$, a bayesian makes statements about the probability that $\theta$ on a specific value.

#### Bayes Theorem:
Moving on from the philosophical differences in how we describe results, let's discus how a bayesian approach actually differs in practice. To understand this, we will need to use probability theory. We can approach our question by considering the joint probability of our data and $\theta$ occurring together, otherwise written as $P(y, \theta)$. This probability can be rederived using basic rules of conditional probability and written a number of different ways, as shown below...   

$$ P(y, \theta) = Pr(\theta|y)Pr(y) = Pr(y|\theta) Pr(\theta)$$  

When we breakdown these probability statements, we find that the probability of both y and $\theta$ occurring together is the same as the probability of y occurring at all multiplied by the probability of $\theta$ occurring given that y also occurs (this can also be written with y and $\theta$ reversed). Using basic algebra, we can rearrange our equation to create the below statement, also referred to as Bayes Theorem.  


$$ Pr(\theta|y) = \frac{Pr(y|\theta) Pr(\theta)}{Pr(y)}$$
[Broad description]

#### The Components

**Likelihood** - XXX [Confusing nomenclature]  

**Prior Distribution** - XXX  [Defining but not exlusive component of bayesian analysis] [Informative priors]. [What can be a prior?] [Real data] [Expectations] [Benefits]  

[Uninformative priors] In the same way that a prior can represent our knowledge of a parameter, it can also be used to represent that we don't have any prior knowledge of a system and adjust our estimates accordingly, [Benefits of this]  

**Marginal Distribution** - XXX  [Probability of the data] [Can be calculated but doesn't have to be] [Explain basics the segue to...]  

**Joint Distribution** - XXX [Product of the likelihood and the prior] [Proportional to the Posterior. Means that where the joint distribution is maximized, so too will the posterior be maximized. Allows us to ignore the marginal distribution]  

**Posterior Distribution** - [This is the most important quantity in Bayesian inference, goal of the analysis.] [Represents information about unknown parameters based on the data and priors provided.] 

[Every posterior distribution used to be a prior]

#### Our Turkey Example

[reference turkey example]

### MCMC: Sampling from the Posterior

[Bayesian Inference is just counting]

[Simulated draws from the posterior]

[Sampling Approaches]

### Bayesian vs Frequentist

So now that you have at least a broad understanding of the differences in philosophy between the two approaches, lets get into more detail on the similarities and differences between them. We will start broad and probably reiterate the major points of the above sections and then get into the smaller scale details.  

**Definition of Unknown Parameters** - XXX  

**Randomness vs Uncertainty** - [Randomness (frequentist) vs uncertainty (Bayesian) - Nothing is actually random, if we had enough information and a powerful enough computer, you could predict almost any natural system in theory]  

**Pior information** - XXX  

**Ease of Use** - XXX  

**Computational Limitations** - XXX  


[Kery and Schaub - Bayesian pop analysis ch 2.4]

[Held and Bove - Likelihood and Bayesian Inference ch 3]

[Hobbs and Hooten - 4.2 Likelihood profiles] 



### Sources and Other Resources

This module is a synthesis of ...
  
<div style="margin-left: 1em;">  
  Hobbs and Hooten - Bayesian Models: A Statistical primer for Ecologists  
  McElreath - Statistical Rethinking: A Bayesian Course with Examples in R and Stan  
  Kery - Introduction to WinBUGS for Ecologists: A Bayesian approach to regression, ANOVA, mixed models and related analyses  
  Kery and Schaub - Bayesian Population Analysis using WinBUGS: A Hierarchical Perspective
</div>
  
I have also found the below resources useful in better understanding bayesian concepts and applications. 
  
  <div style="margin-left: 1em;">  
  [Olivier Giminez's Youtube Channel](https://www.youtube.com/c/OlivierGimenez)  
  [Richard McElreath's Youtube Channel](https://www.youtube.com/channel/UCNJK6_DZvcMqNSzQdEkzvzA/about)  
  [ritvikmath Youtube Channel](https://www.youtube.com/c/ritvikmath)  
  [Fox 2011 - Frequentist vs. Bayesian statistics: resources to help you choose](https://dynamicecology.wordpress.com/2011/10/11/frequentist-vs-bayesian-statistics-resources-to-help-you-choose/)  
  [McGill 2013 - Why saying you are a bayesian is a low information statement](https://dynamicecology.wordpress.com/2013/06/19/why-saying-you-are-a-bayesian-is-a-low-information-statement/)  
      
  </div>